name: flutter_install_referrer
description: "Bundeling Flutter install referrer plugin"
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bundeling.flutter_install_referrer
        pluginClass: FlutterInstallReferrerPlugin
